stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "This is build stage"

test-job:
  stage: test
  script:
    - echo "This is test stage"

deploy-job:
  stage: deploy
  only:
    - master
  script:
    - apt-get install -y lftp
    - lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; set ssl:verify-certificate no; mirror -R -e ./ /public_html/"
    - echo "This is deploy stage"
